package com.edu.cit.Learnify.DTO;

import lombok.Data;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

import java.util.List;

// ─── Request: Start a new game ───────────────────────────────────────────────
@Data
class StartGameRequest {
    private String playerName;
}

// ─── Request: Submit an answer ───────────────────────────────────────────────
@Data
class AnswerRequest {
    private String selectedOption;
}

// ─── Response: Question generated by Gemini ──────────────────────────────────
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
class QuestionResponse {
    private String sessionId;
    private String question;
    private List<String> options;
    private String enemyName;
    private int playerHp;
    private int enemyHp;
    private int playerMaxHp;
    private int enemyMaxHp;
    private int score;
    private int streak;
}

// ─── Response: Answer result ─────────────────────────────────────────────────
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
class AnswerResponse {
    private boolean correct;
    private String correctAnswer;
    private String explanation;
    private String funFact;
    private String feedback;         // Gemini's encouraging message
    private int damageDealt;         // damage to enemy (if correct)
    private int damageTaken;         // damage to player (if wrong)
    private int playerHp;
    private int enemyHp;
    private int score;
    private int streak;
    private String status;           // "active" | "won" | "lost"
    private List<String> battleLog;
    private String enemyAction;      // description of what the enemy did
}

// ─── Response: Full game state ────────────────────────────────────────────────
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
class GameStateResponse {
    private String id;
    private String playerName;
    private int playerHp;
    private int playerMaxHp;
    private String enemyName;
    private String enemyType;
    private int enemyHp;
    private int enemyMaxHp;
    private int enemyLevel;
    private String currentTurn;
    private String status;
    private int score;
    private int questionsAnswered;
    private int correctAnswers;
    private int streak;
    private List<String> battleLog;
}
